<<<<<<< HEAD
import Head from "next/head"
import Navbar from "../../components/nav"
import Mock from "./board"
=======
import Head from "next/head";
import Navbar from "../../components/nav"
import styled from 'styled-components'
>>>>>>> fc6f57c1f3a78d1ba7e13394dfc60be34003adca

function Heading() {
  return (
    <>
      <Head>
        <title>Raffle Board | Quantum Fair</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://i.ibb.co/xJxBBbv/QF-Media-kit-ref.png" />
      </Head>
    </>
  )
}

function Board() {
    return (
  <>
<<<<<<< HEAD
    <Heading />
    <Navbar />  
    <Mock />  
=======
    <Heading/>
    <Navbar />    
>>>>>>> fc6f57c1f3a78d1ba7e13394dfc60be34003adca
  </>
 )
}

export default Board