import Head from "next/head";
import { Body } from './home'
import Navbar from "../components/nav";

function Heading() {
  return (
    <>
      <Head>
        <title>Quantum Fair</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

export default function Home() {
  return (
    <>
      <Heading/>
      <Navbar />
     
    </>
  );
}
