import Head from "next/head";
import { Body } from './home'
import Navbar from "../components/nav";
import { Flex } from "@chakra-ui/react";

function Heading() {
  return (
    <>
      <Head>
        <title>Quantum Fair</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://i.ibb.co/xJxBBbv/QF-Media-kit-ref.png" />
      </Head>
    </>
  )
}

export default function App() {
  return (
  <>
  <Heading/>
    <Flex h="100vh" bg="#efefef">    
      <Navbar /> 
      <hr/>
    </Flex>
  </>  
  );
}
